"""
Create a program that uses comparison operators (< > <= >=).
You must use the class' datafile, 'responses.csv' and analyze it
    to make at least 2 interesting observations.
You may use user input to add interactivity to the program.
You must design your algorithm in English first, then translate it to Python code.
Test as you go! Describe in your comments what steps you took to test your code.
"""
""" My assignment
I plan to make a program that finds that asks the user a survey, and from that the program will find the top 3 names with the 
most similarities to the results of the survey it will display the results along with a unique comment based on the score of each individual
person.

1.) I create a bunch of temporate variables and empty lists to house data like, user response, survey, names, rankings, tallys, placement and scores.
2.)I then use a for loop to dispense questions in the list one by one and puttig the users response into an empty list
3.) Now the program will use a nested for loop to check each indidual line/person and give them a scoreon how many similarities they have
4.) I put in all those scores in a list. I run a nested for loop 3 times with a for loop to find the hghest value, each time it runs the highest value
is subtracted from the origional list so a new highest value will come, each of these highest values is put into a list generating a list of 
the top 3 names.
5.) As an output I use a for loop to print out each individual name along with a unique comment based on 
the ammount of similarities you to have

ex.) What is your name? Jeremy wong
What is your favourite number?8
What is your favourite pet?cat
What is your favourite subject?math
What is your favourite sport?Football
'What is your favourite sport to watch?Football
'What is your favourite genre of music?K-pop
'What is your favourite movie genre?Adventure
'What is your favourite place to eat?'bubble waffle
Your first best match is serene lee
Wow you have alot in common with them!
Your second best match is jayden wong
We all have our differences
Your third best match is gabe armour
We all have our differences
"""
file = open("2.4/responses.csv")
#Opens the database file once
survey = ['What is your favourite number?', 'What is your favourite pet?', 'What is your favourite subject?', 'What is your favourite sport to play?', 'What is your favourite sport to watch?', 'What is your favourite genre of music?', 'What is your favourite movie genre?', 'What is your favourite place to eat?']
#This list will store the survey questions that are asked to the user
urlist = []
#This empty list will contain the user's response
first = ''
#this variable will contain the person with the highest similarity to the user
rank = []
#this empty list will contain the list of scores 
#generated by the first for loop nested section
listofnames = []
#This empty list contains all the names in the database
best = []
#list to contain the top 3 names with most similarity to the user
placementofnum = 0
#Variable to store the current placement number of the best winner 
rankscore = []
#empty list to store the score of the top 3 most similar names
name = input('what is your full name? ').lower().strip() 
#gets the name of the user and stores it in a variable this is seperate from the user survey results
for quesion in survey:
    #This for loop will repeatedly ask the questions in the survey 
    # variable one at a time
    #Then will use append to put each response from the user into 
    #urlist variable
    question = input(quesion).lower().strip()
    urlist.append(question)
#>>>>>>>>>>>>>>>>>>>>>>>>>>>
junk = file.readline()
#Reads and discards the first line of the database which is 
#useless and may cause future errors
for line in file: 
    #This for loop will iterate another for loop
    #for as many lines there are in the file of 
    #the database
    tally = 0
    #resets the tally to 0 after the score of the person is 
    #recorded in rank list
    for x in range(len(urlist)):
        #This for loop will run for how many qualities
        #in urlist
        personlist = line.lower().split(',')
        #turns each line into a list and stores it in a variable
        if name in personlist:
            continue
        #checks if the line contains the users name and skips over it
        if urlist[x] in personlist:
        #checks each individual quality in personlist 
        #and adds one to the tally for each quality
            tally += 1
    rank.append(tally)
    #at the end of the for loop it adds the value of the tally to a list
    #before it is reset to 0
    listofnames.append(personlist[1])
    #at the end of the for loop adds the name of the person
    #to the listofnames before personlist is reset to the next person
#print(str(rank))
#>>>>>>>>>>>>>>>>>>>>>>>>>>>

for a in range(3):
    #this for loop will run 3 times
    score = -1
    bestmatchscore = 0
    #reseting the score and bestmatchscore variables 3 times
    if first in listofnames:
    #checks if that value of first is in the list
    #if so, it will remove the value and the score 
    # then allowing the for loop to continue
    #finding the most similar person without the value of first
            listofnames.remove(first)#new code usage(ask mrchin to explain)
            rank.pop(placementofnum)#new code usage(ask mrchin to explain)
            #print('removed first person')
    for i in rank:
        #iterates for the ammount of values in rank list
        score += 1
        #records the current placement of the value eg.
        # (5, 6, 7)
        #if the for loop is checking 7
        #score would equal 3 
        if i > bestmatchscore:
        #checks if i is greater than the bestmatchscore
            bestmatchscore = i
        #if so, sets the bestmatch score = 1 & 
        #stores the name of the person in the first variable
        #stores the placement of the score in placementofnum
            first = listofnames[score]
            #print('variable first has changed')
            placementofnum = score
    rankscore.append(bestmatchscore)
    best.append(first)
    #at the end of the for loop adds the values and scores of the best
    #person to two different lists (this goes on 3 times)
    #eg ['serene lee', 'jayden wong', 'gabe armour']
#print(str(best))
#print(str(rankscore))
place = ['first', 'second', 'third']
#temporate list to hold words
#I didn't want to write 9 if statements
#I used a for loop that will run for the ammount of values in rankscore list
#since it will run 3 times, Your    best match is   . is being written 3 times
#each time the rank is different.
#I also used if statements to check each individual score if it is greater 
#or equal to 4 less than 4 and greater or equal to 2 based on those conditions, the program
#will dispense a different response for each of the 3 names
for b in range(len(rankscore)):
    print('Your ' + place[b] + ' best match is ' + str(best[b]))
    if rankscore[b] >= 4:
        print('Wow, you have alot in common with them!')
    elif rankscore[b] < 4 and rankscore[b] >= 2:
        print('We all have our differences.')
    else:
        print('Wow, your truly unique!')

