
'''
-Has import all the modules needed for the program
-Created lists and variables to house all the data use for the program
-stardata will house the star colour and percent compositon for each star
    ex. [('red', 90.24322323), ('blue', 67.67676767)]
-secondstardata will house the other data generated by colour 
    ex. [('M', '2100k-3400k', 'About 5-9 times the boiling point of water!'), ('K', '3400k-4900k', 'Around 2 times the melting point of Iron!') 
'''
import time
t0 = time.time()
print('Beginning program... \n \n')
# from PIL import Image
import sunfunctions
t1 = time.time()
print('Processing images... \n \n')
tstart = time.time()

'''
-Get a list of pictures of stars and have a for loop iterate a nested for loop
-Use a list of star names for easy codeoutput formating
-use a for loop to iterate a nested for loop
    -nested for loop will iterate over the entire image and check the indicators:
        -red
        -orange
        -yellow
        -white
        -blue
    as those are what most star colours are.
    This program will use multiple variables set at 0.01
    (later we use these values in division so we use 0.01 so we don't divide by 0)
    at the end of the nested loop, will generate a list of total pixels in that color 
    for the star. EX:
        [10123, 6767, 414141, 0.01, 0.01]
    -for loop will iterate this nested for loop 10 times with the 10 different images
'''
stars = ['6.7/stars/notsun.webp', '6.7/stars/vega.jpg', '6.7/stars/alpha_centauri_a.jpg', '6.7/stars/epilison.jpg', '6.7/stars/Mr_Chin.jpg', '6.7/stars/Naos.png', '6.7/stars/tau_ceti.webp', '6.7/stars/sirius_a.jpg', '6.7/stars/proxima_centauri.jpg', '6.7/stars/antares.avif']
names = ['notsun', 'vega', 'alpha_centauri_a', 'epilison', 'Mr_Chin', 'Naos', 'tau_ceti', 'sirius_a', 'proxima_centauri', 'antares']
stardata = []
secondstardata = []
for a in range(len(stars)):
    yellow = 0.01
    blue = 0.01
    red = 0.01
    orange = 0.01
    white = 0.01
    tstar = time.time()    
    file = Image.open(stars[a])
    star = file.load()
    width, height = file.width, file.height
    for i in range(width):
        for j in range(height):
            r = star[i,j][0]
            g = star[i,j][1]
            b = star[i,j][2]
            if sunfunctions.yellow(r, g, b): 
                yellow += 1
            if sunfunctions.red(r, g, b):
                red += 1
            if sunfunctions.orange(r, g, b):
                orange += 1
            if sunfunctions.blue(r, g, b):
                blue += 1
            if sunfunctions.white(r, g, b):
                white += 1
    all = [red, orange, yellow, white, blue]


    '''
    Will now use custom functions to generate data based on the list 'all'
    Startype - calculates the majority colour of the star and generates it's percentage
        ex: input:
                [10123, 6767, 414141, 0.01, 0.01], 
            output: 
                ('yellow', 67.676767)
    starclass - creates comments and assigns class stars and aproximate tempertures to stars based on color
        ex: input: 
                'red', 
            output: 
                'M', '2100k-3400k', 'About 5-9 times the boiling point of water!'
    '''
    startype = sunfunctions.startype(all)
    stardata.append(startype)
    secondstardata.append(sunfunctions.starclass(startype[0]))
    tend = time.time()
    '''
        Output the data in stat-sheet table like format to layout data in a short readable way
    '''
    output =  '''
    name:{} 
    time: {:.3f}s
    colour: {}
    colour percentage: {:.3f}%
    star type:{}
    Temp: {}
    {}
    \n
    '''.format(names[a], tend-tstar, stardata[a][0], stardata[a][1], secondstardata[a][0], secondstardata[a][1], secondstardata[a][2])
    print(output)
